#!/usr/bin/env sh

# needed by gnome-terminal to preserve path
[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

[[ -d "$HOME/.local/bin" ]] && PATH="$HOME/.local/bin:$PATH"
[[ -d "$HOME/.cargo/bin" ]] && PATH="$HOME/.cargo/bin:$PATH"

[[ -n "$DISPLAY" && "$TERM" = "xterm" ]] && export TERM=xterm-256color

export EDITOR="vim"
